---
apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
  annotations: {}
  name: nodejs
  namespace: nodejs-ex
spec:
  running: false
  template:
    metadata:
      labels:
        name: nodejs
        app: nodejs
    spec:
      nodeSelector:
        kubernetes.io/hostname: ckn1.virtomation.com
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
            volumeName: nodejs-vol0
          - disk:
              bus: virtio
            name: cloudinitdisk
            volumeName: cloudinitvolume
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      volumes:
      - name: nodejs-vol0
        registryDisk:
          image: kubevirt/fedora-cloud-registry-disk-demo
      - name: cloudinitvolume
        cloudInitNoCloud:
          userDataBase64: I2Nsb3VkLWNvbmZpZwpzc2hfcHdhdXRoOiBUcnVlCmRpc2FibGVfcm9vdDogZmFsc2UKc3NoX2F1dGhvcml6ZWRfa2V5czoKLSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUURWYURpRDlJOFdZdDNrMXVVYzkzWEF6T1R5a2JtUUJqWjFLS2ZCeUlQeTVMR09NMTJFeno2QTBtemtiNlljKzdZTWNOd3l4WlNhaURLWFpFU3JGWnlZUjlhajVIZEYyT1Vka3liRU5TblFOMld3aVVhQXE0azBiVGI5TjZqb0tzMndNVHlMZGNHVEdUY0pVZkdna0ZyM3B6QjhOckNIYU1PY3hZYWJrL0RpWUs4L2JLUGxhTUdNK0gvSGl6a2UyWnhnZFJGa0hkTUErTFNjR29hbnVNVGxLK2d0Rks0cHBaUEJiNmtxN0JwN0Jad3Rob3kvWW5Wd2F1TDVITmVrN0drNW5LMnpwNkV2ZXZYMmEyNi9lOG80U3NVaHN3eDFqK2dCbDErNzU3YXlGSTMycEdjc0FBN3o2WXBLOTR1dWtZVGNYa0xmYi8xamQ1Sk04dGlpcXpQNSB1c2VyQDQwM2E3YjZiNGY5Ngo=

---
apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
  annotations: {}
  name: mongodb
  namespace: nodejs-ex
spec:
  running: false
  template:
    metadata:
      labels:
        name: mongodb
        app: mongodb
    spec:
      nodeSelector:
        kubernetes.io/hostname: ckn2.virtomation.com
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
            volumeName: mongodb-vol0
          - disk:
              bus: virtio
            name: cloudinitdisk
            volumeName: cloudinitvolume
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      volumes:
      - name: mongodb-vol0
        registryDisk:
          image: kubevirt/fedora-cloud-registry-disk-demo
      - name: cloudinitvolume
        cloudInitNoCloud:
          userDataBase64: I2Nsb3VkLWNvbmZpZwpzc2hfcHdhdXRoOiBUcnVlCmRpc2FibGVfcm9vdDogZmFsc2UKc3NoX2F1dGhvcml6ZWRfa2V5czoKLSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUURWYURpRDlJOFdZdDNrMXVVYzkzWEF6T1R5a2JtUUJqWjFLS2ZCeUlQeTVMR09NMTJFeno2QTBtemtiNlljKzdZTWNOd3l4WlNhaURLWFpFU3JGWnlZUjlhajVIZEYyT1Vka3liRU5TblFOMld3aVVhQXE0azBiVGI5TjZqb0tzMndNVHlMZGNHVEdUY0pVZkdna0ZyM3B6QjhOckNIYU1PY3hZYWJrL0RpWUs4L2JLUGxhTUdNK0gvSGl6a2UyWnhnZFJGa0hkTUErTFNjR29hbnVNVGxLK2d0Rks0cHBaUEJiNmtxN0JwN0Jad3Rob3kvWW5Wd2F1TDVITmVrN0drNW5LMnpwNkV2ZXZYMmEyNi9lOG80U3NVaHN3eDFqK2dCbDErNzU3YXlGSTMycEdjc0FBN3o2WXBLOTR1dWtZVGNYa0xmYi8xamQ1Sk04dGlpcXpQNSB1c2VyQDQwM2E3YjZiNGY5Ngo=
---
kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: nodejs-ex
  labels:
    kubevirt.io: virt-launcher
    kubevirt.io/domain: mongodb
spec:
  selector:
    kubevirt.io: virt-launcher
    kubevirt.io/domain: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---
kind: Service
apiVersion: v1
metadata:
  name: nodejs
  namespace: nodejs-ex
  labels:
    kubevirt.io: virt-launcher
    kubevirt.io/domain: nodejs
spec:
  selector:
    kubevirt.io: virt-launcher
    kubevirt.io/domain: nodejs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodejs
  namespace: nodejs-ex
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: nodejs.ingress.virtomation.com
    http:
      paths:
      - backend:
          serviceName: nodejs
          servicePort: 8080
